# Generated by Django 3.0.6 on 2020-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_auto_20200625_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default/defaultuser.png', upload_to='user_ProfilePics'),
        ),
    ]
